### PR TITLE
feat: Enhance text selection menu in reader

### PR DESCRIPTION
**Pull request by starry-shivam**

### CODE REVIEW

**Comment by Acclorite** [comment]
Just to note. This custom solution is greatly undeveloped, even though it "kinda" works, I'd replace it with new library/solution as fast as there is one.

**Comment by starry-shivam** [comment]
> Just to note. This custom solution is greatly undeveloped, even though it "kinda" works, I'd replace it with new library/solution as fast as there is one.

Yeah, I've read a few threads on Google's Issue Tracker related to that. In most of them, they mentioned that they would implement a proper selection menu, similar to what was available in the XML view system, for Compose in future releases. Well, fast forward two years, and we're still stuck with just one "copy" option. So yeah, it's better than nothing. Thanks for that! I wanted to do something similar but always felt too lazy to look into it, or I was occupied with something else most of the time.

Btw, your reader options/settings also look neat! Don't mind if i pick some of those haha

**Comment by Acclorite** [comment]
> Well, fast forward two years, and we're still stuck with just one "copy" option.

Yeah, that's what annoys me. The topic has minimal movement, same with scrollbar, but for scrollbar there at least is a library..

To make this selection container, I literally spent about a week of reading wiki, stackoverflow and some other sources. This is super inconvenient and had to be fixed and improved long time ago.

> Btw, your reader options/settings also look neat!

Really? I plan on reworking them, I feel like your app's settings look much better :D

> Don't mind if i pick some of those haha

Well I also am interested in some of your design decisions. I prefer traditional Material3, but your has some interesting decisions ;)

**Comment by starry-shivam** [comment]
> Yeah, that's what annoys me. The topic has minimal movement, same with scrollbar, but for scrollbar there at least is a library..

Exactly, and they keep deprecating existing solutions in favor of half-baked things. For example, they've marked `TextToolbar` as deprecated without even providing any API to replace it, at least in Compose. I'm not sure about XML since you don't really need custom implementation in XML most of the time.

> To make this selection container, I literally spent about a week of reading wiki, stackoverflow and some other sources. 

Thanks for your efforts! If I hadn't stumbled upon your code, I wouldn't have worked on this anytime soon due to the similar experience you had to go through.

> Really? I plan on reworking them, I feel like your app's settings look much better :D 

Yep! I specifically liked settings like line & paragraph spacing and similar things. The settings related to the reader were organized neatly in a bottom sheet.

> Well I also am interested in some of your design decisions. I prefer traditional Material3, but your has some interesting decisions ;)

In my previous open-source app (GreenStash), I had mostly used traditional Material 3 design components, so I wanted to try something different with this one. :)

**Comment by Acclorite** [comment]
> Yep! I specifically liked settings like line & paragraph spacing and similar things. The settings related to the reader were organized neatly in a bottom sheet.

I try extend customization to it's limits as I there is not really too much to do with plain text. As for organization I follow one simple rule — all settings should be easily accessible from Settings screen. I try to not make some random options in some screen you would need to search for 10 minutes to find, and seems like it's working as of now.

**Comment by starry-shivam** [comment]
> > Yep! I specifically liked settings like line & paragraph spacing and similar things. The settings related to the reader were organized neatly in a bottom sheet.
> 
> I try extend customization to it's limits as there is not really much to do with plain text. As for organization I follow one simple rule — all settings should be easily accessible from Settings screen. I try to not make some random options in some screen you would need to search for 10 minutes to find, and seems like it's working as of now.

Yep, I also need to improve and add more options to my reader settings. It's very barebones right now, haha

**Pull request merged**
