### PR TITLE
Add Chinese Simplified Translation

### PR DESCRIPTION
**Pull request by WeiguangTWK**
A string "Made with ❤ by Shivam" is left in English because I think it is better to do so :)

Also options of "Ebook reader" is missing from string xml so I can't translate it.

### CODE REVIEW

**Comment by WeiguangTWK** [comment]
@starry-shivam  OK! And I will copy these comments to zh-rCN xml file and commit

**Review by starry-shivam — COMMENTED** [review]
Thank you! Please wait until I export those two missing strings so you can translate them as well, and then we'll move ahead to merge it

**Comment by starry-shivam** [comment]
@WeiguangTWK I've exported and merged the main branch into your PR. Now, you can add translations for those missing strings.

**Review by starry-shivam — APPROVED** [review]
Looks good!

**Comment by WeiguangTWK** [comment]
@starry-shivam Yeaaaa it works

**Comment by starry-shivam** [comment]
Merged! Thanks :)

**Pull request merged**
